import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider";

import "../globals.css";
import MainLayout from "@/layout/main-layout";
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <MainLayout>
            <div className="flex items-center justify-between">
              <Link href="/" className="font-semibold text-lg">
                Nextjs x Sanity
              </Link>
              <ModeToggle />
            </div>
            <hr className="my-5" />
            {children}
          </MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
